sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t miguel0ey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true miguel0ey/docker-react npm run test -- --coverage
